spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///photo_manage_system?useSSL=true
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 3

#Mybatis配置
mybatis:
  type-aliases-package: com.ydb.entity
  mapper-locations:  classpath:static/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#日志配置
logging:
  level:
    com.ydb.dao.IPhotoDao: debug
    com.ydb.dao.ICommentDao : debug

#SpringSecurity配置
security:
  basic:
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8


swagger:
  basePackage:  com.ydb.controller
  title: 照片管理系统请求接口测试
  version : V1.0