spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///photo_manage_system?useSSL=true
    username: root
    password: 123456


#Mybatis配置
mybatis:
  type-aliases-package: com.ydb.entity
  mapper-locations:  classpath:static/mapper/*.xml

#日志配置
logging:
  level:
    com.ydb.dao.IPhotoDao: debug


#SpringSecurity配置
security:
  basic:
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8


